version: '3.7'

services: 

  e2e: 
    build: 
      dockerfile: tools/docker/e2e/Dockerfile
      context: ${PWD}
    command: npx playwright test
    volumes: 
       - ${PWD}/test-results:/build/test-results