name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: docker-compose --file tools/docker/docker-compose.e2e.yml up --build
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test_results
          path: test-results
          retention-days: 45