name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  e2e:
    uses: ./.github/workflows/execute-docker-compose-and-publish-results.yml
    with:
      tests-type: e2e
      tests-result-path: test-results

  api-tests:
    uses: ./.github/workflows/execute-docker-compose-and-publish-results.yml
    with:
      tests-type: api
      tests-result-path: test-results-api
