name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e:
    uses: ./.github/workflows/execute-docker-compose-and-publish-results.yml
    with:
      tests-type: e2e
      tests-result-path: test-results

  api-tests:
    uses: ./.github/workflows/execute-docker-compose-and-publish-results.yml
    with:
      tests-type: api
      tests-result-path: test-results-api

  deploy-results:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Prepare test reports
    runs-on: Ubuntu-latest
    needs: 
      - e2e
      - api-tests
    steps:
      - run : |
          mkdir _site
          echo '<html><body><ul>
                <li><a href="api/test">api test results</a></li>
                <li><a href="web/test-report">web app test results</a></li>
              </ul></body></html>' >> _site/index.html
      - uses: actions/download-artifact@v3.0.1
        with:
         name: test_results_api
         path: _site/api/
      - uses: actions/download-artifact@v3.0.1
        with:
         name: test-results
         path: _site/web/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - run : |
          location=${{ steps.deployment.outputs.page_url }}
          echo '## Tests results published' >> $GITHUB_STEP_SUMMARY
          echo '[GitHub Pages]('$location')'  >> $GITHUB_STEP_SUMMARY

