name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e:
    uses: ./.github/workflows/execute-docker-compose-and-publish-results.yml
    with:
      tests-type: e2e
      tests-result-path: test-results

  api-tests:
    uses: ./.github/workflows/execute-docker-compose-and-publish-results.yml
    with:
      tests-type: api
      tests-result-path: test-results-api

  deploy_results:
    runs-on: Ubuntu-latest
    needs: 
      - e2e
      - api-tests
    steps:
      - run: echo 'deployment'
