name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  e2e:
    name: Build and run e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: docker-compose --file tools/docker/docker-compose.e2e.yml up --build
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test_results
          path: test-results
          retention-days: 45

  api-tests:
    name: Build and run api tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: docker-compose --file tools/docker/docker-compose.api.yml up --build
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test_results_api
          path: test-results-api
          retention-days: 45 
