on:
  workflow_call:
    inputs:
      tests-type:
        required: true
        type: string
      tests-result-path:
        required: true
        type: string
jobs:
  execute-tests:
    name: Build and run ${{ inputs.tests-type }} tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Docker Compose
        run: docker-compose --file tools/docker/docker-compose.${{ inputs.tests-type }}.yml up --build
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test_results_${{ inputs.tests-type }}
          path: ${{ inputs.tests-result-path }}
          retention-days: 45 